### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by nisrulz** [lawloretienne/SharedElementTransition#1]
When running the app i get the below on clicking one of the items in the list

```
FATAL EXCEPTION: mainProcess: com.etiennelawlor.sharedelementtransition, PID: 1814
 java.lang.IllegalArgumentException: Shared element must not be null
at android.app.ActivityOptions.makeSceneTransitionAnimation(ActivityOptions.java:561)
at android.support.v4.app.ActivityOptionsCompat21.makeSceneTransitionAnimation(ActivityOptionsCompat21.java:45)
at android.support.v4.app.ActivityOptionsCompat.makeSceneTransitionAnimation(ActivityOptionsCompat.java:171)
at com.etiennelawlor.sharedelementtransition.fragments.CheesesFragment.onItemClick(CheesesFragment.java:159)
 at com.etiennelawlor.sharedelementtransition.adapters.CheesesAdapter$1.onClick(CheesesAdapter.java:97)
at android.view.View.performClick(View.java:5198)
 at android.view.View$PerformClick.run(View.java:21147)
at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by lawloretienne** [comment]
I cannot reproduce.  Can you give me more details?  Phone specs, O.S. version. Which screen are you looking at?  Which item in the list did you click?

**Comment by KatharinaSick** [comment]
I'm facing the same issue:

`FATAL EXCEPTION: main
                                                                                           Process: com.etiennelawlor.sharedelementtransition, PID: 21573
                                                                                           java.lang.IllegalArgumentException: Shared element must not be null
                                                                                               at android.app.ActivityOptions.makeSceneTransitionAnimation(ActivityOptions.java:590)
                                                                                               at android.support.v4.app.ActivityOptionsCompat21.makeSceneTransitionAnimation(ActivityOptionsCompat21.java:45)
                                                                                               at android.support.v4.app.ActivityOptionsCompat.makeSceneTransitionAnimation(ActivityOptionsCompat.java:171)
                                                                                               at com.etiennelawlor.sharedelementtransition.fragments.CheesesFragment.onItemClick(CheesesFragment.java:159)
                                                                                               at com.etiennelawlor.sharedelementtransition.adapters.CheesesAdapter$1.onClick(CheesesAdapter.java:97)
                                                                                               at android.view.View.performClick(View.java:5205)
                                                                                               at android.view.View$PerformClick.run(View.java:21164)
                                                                                               at android.os.Handler.handleCallback(Handler.java:745)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:171)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Phone: ZTE Axon 7 (Android 6.0.1, MiFavor UI 4.0)
The exception appeared on both screens with all list items

Thanks :)
